# Generated by Django 3.2.7 on 2022-01-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Разделения',
                'verbose_name_plural': 'Разделении',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateField(verbose_name='Дата выписки предписания')),
                ('date_answer', models.DateField(verbose_name='Дата исполнения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories', verbose_name='Предприятие(служба)')),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Выполнил(а)')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
