# Generated by Django 4.0.1 on 2022-01-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='client',
            new_name='fio',
        ),
    ]
