# Generated by Django 4.0.1 on 2022-01-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alldocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldocuments',
            name='when',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
