# Generated by Django 4.0.1 on 2022-01-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_alldocuments_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AllDocuments',
        ),
        migrations.AddField(
            model_name='alldocument',
            name='plans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documentnames'),
        ),
    ]
