# Generated by Django 4.0.1 on 2022-01-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alldocument_when'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Разделения', 'verbose_name_plural': 'Разделении'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='documents',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories', verbose_name='Предприятие(служба)'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='date',
            field=models.DateField(verbose_name='Дата выписки предписания'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='date_answer',
            field=models.DateField(verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='fio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Выполнил(а)'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.DeleteModel(
            name='AllDocument',
        ),
        migrations.DeleteModel(
            name='DocumentNames',
        ),
    ]
